name: Mechanic Shop API Tests

on:
    push:
        branches:
            - deployment-cicd-pipeline

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout respository
              uses: actions/checkout@v6

            - name: Set up Python
              uses: actions/setup-python@v6
              with:
                  python-version: 3.14
                  cache: pip

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install -r requirements.txt

            - name: Check Python syntax
              run: python -m compileall app flask_app.py

    test:
        needs: build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout respository
              uses: actions/checkout@v6

            - name: Set up Python
              uses: actions/setup-python@v6
              with:
                  python-version: 3.14

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install -r requirements.txt

            - name: Run tests
              run: python -m unittest discover -s tests -p "test_*.py"

    deploy:
        needs: test
        runs-on: ubuntu-latest

        steps:
            - name: Checkout respository
              uses: actions/checkout@v6

            - name: Set up Python
              uses: actions/setup-python@v6
              with:
                  python-version: 3.14

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install -r requirements.txt

            - name: Deploy to production
              uses: johnbeynon/render-deploy-action@v0.0.8
              with:
                  service-id: ${{ secrets.SERVICE_ID}}
                  api-key: ${{secrets.RENDER_API_KEY}}
